apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: duckcon-example
spec:
  entrypoint: main

  templates:
    - name: main
      steps:
        - - name: hello-world-x5
            template: hello-world
            withSequence:
              count: "10"

    - name: process
      container:
        image: junaidrahim/duckcon-example:latest
        command: [cowsay]
        args: ["hello world!"]
